import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import SVGlogo from '../public/assets/images/prosegman-logo.svg'
import SVGnoun_map_106497 from '../public/assets/images/noun-map-106497.svg'
import SVGnoun_phone_4530342 from '../public/assets/images/noun-phone-4530342-1.svg'
import SVGconoceMas from '../public/assets/images/Path_60.svg'
import EmblaCarousel from "../components/EmblaCarousel";

const SLIDE_COUNT = 9;
const slides = Array.from(Array(SLIDE_COUNT).keys());


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a className={styles.whats} href="#"></a>
        <div className={styles.contenedorMainAux}>
          <header className={styles.Header}>
            <nav className={styles.HeaderBar}>
              <div className={styles.HeaderContainer}>
                  <a><SVGlogo /></a>
                  <a href="#">INICIO</a>
                  <a href="#">SERVICIOS</a>
                  <a href="#">EMPRESAS</a>
                  <a href="#">CONTACTO</a>
              </div>
            </nav>
            <div className={styles.HeaderTitle}>
              <h1>
                  Diseñamos e instalamos <strong>soluciones</strong><br></br>
                  <strong>de seguridad electrónica</strong> y digital<br></br>
                  salvaguardando bienes corporativos y <br></br>
                  de industrias diversas desde hace <br></br>
                  <strong>más de 10 años</strong>
              </h1>
            </div>
            <a className={styles.conoceMas_Conteiner} href="#">
              <p>Conoce Más</p>
              <SVGconoceMas />
            </a>
          </header>

          <div className={styles.conteinerAux}>
            <div className={styles.ContenedorPrincipal}>

              <section className={styles.services}>
                <h2 className={styles.servicios__title}>Servicios</h2>

                <div className={styles.servicios__text__conteiner}>
                  <p className={styles.servicios__text}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
                    nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse
                  </p>
                </div>

                <div className={styles.grid}>
                  <div className={styles.grid__conteiner}>
                    <card>
                      <div className={styles.cardTitle}>
                        <h3>Levantamiento en campo</h3>
                      </div>
                      <div className={styles.cardInfo}>
                        <p>Aseguramos la información de cada proyecto</p>
                      </div>
                    </card>

                    <card>
                      <div className={styles.cardTitle}>
                        <h3>Diseño e ingeniería</h3>
                      </div>
                      <div className={styles.cardInfo}>
                        <p>Una solución a tus necesidades</p>
                      </div>
                    </card>

                    <card>
                      <div className={styles.cardTitle}>
                        <h3>Venta e Instalación de equipo</h3>
                      </div>
                      <div className={styles.cardInfo}>
                        <p>Nos encargamos de proveer</p>
                      </div>
                    </card>

                    <card>
                      <div className={styles.cardTitle}>
                        <h3>Planes de Mantenimiento</h3>
                      </div>
                      <div className={styles.cardInfo}>
                        <p>Conservaremos tu infraestructura 100% funcional</p>
                      </div>
                    </card>

                    <card>
                      <div className={styles.cardTitle}>
                        <h3>Supervisión de Obra</h3>
                      </div>
                      <div className={styles.cardInfo}>
                        <p>Garantizamos la ejecución de implementación</p>
                      </div>
                    </card>
                  </div>
                </div>

                <div className={styles.servicios__text__conteiner}>
                  <p className={styles.servicios__text}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
                    nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse
                  </p>
                </div>

                <EmblaCarousel slides={slides} />





                <div className={styles.conteinerButton}>
                  <button className={styles.servicesButton}>Conoce Más</button>
                </div>
              </section>

              <section className={styles.empresa}>
                <h2>Empresa</h2>
                <p>
                  <span>Utilizamos estandares internacionales en cada una de nuestras áreas,</span>
                  <span>como: NFPA, AFSA, FM, NOM entre otros</span>
                </p>
                <div className={styles.imgConteiner}></div>
                <p>
                  <span>PROSEGMAN le asegura encontrar la solución más adecuada</span>
                  <span>a su necesidad.</span>
                </p>
                <p>
                  <span>En PROSEGMAN no buscamos tener clientes, buscamos relaciones de</span>
                  <span>confianza a largo plazo ofreciendo precios competitivos y cumpliendo</span>
                  <span>con tiempos pactados.</span>
                </p>

                <p>Carrusel de empresas</p>

                <div className={styles.conteinerButton}>
                  <button className={styles.empresaButton}>Conoce Más</button>
                </div>

              </section>

            </div>

          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <section className={styles.footer_left}>
          <div className={styles.footer_left_aux}>
            <h2>Contáctanos</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
              do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <input className={styles.name} placeholder="Nombre completo"></input>
            <input className={styles.email} placeholder="Email o teléfono"></input>
            <input className={styles.textArea} placeholder="Comentario"></input>
            <button className={styles.contactanosButton}>Enviar</button>
          </div>
        </section>

        <section className={styles.footer_right}>
          <div className={styles.listConteiner}>
            <ul>
              <li>
                <SVGnoun_map_106497 />
                <p>
                  <span><strong>Estado de México (Matríz):</strong></span>
                  <span>Av. Gustavo Baz 57, Col. Bosques de Echegaray, C.P. 53310,</span>
                  <span>Naucalpan, Estado de México.</span>
                </p>
              </li>

              <li>
                <SVGnoun_map_106497 />
                <p>
                  <span><strong>Ciudad de México:</strong></span>
                  <span>Av. Tezozomoc27, Col. La Preciosa,</span>
                  <span>C.P. 02406, Del. Azcapotzalco.</span>
                </p>
              </li>

              <li>
                <SVGnoun_map_106497 />
                <p>
                  <span><strong>Querétaro:</strong></span>
                  <span>Central Park Torre II, Armando Birlaín</span>
                  <span>Shafftler 2001 Mezzanine, Col. Centro</span>
                  <span>Sur, C.P. 76090, Queretaro, Qro.</span>
                </p>
              </li>

              <li className={styles.lastchild}>
                <div>
                  <SVGnoun_phone_4530342 />
                  <span>01 (55) 5373 8877</span>
                </div>

                <div>
                  <SVGnoun_phone_4530342 />
                  <span>01 (55) 5373 8902</span>
                </div>
              </li>
            </ul>

            <p className={styles.prosegman}>© 2022 Prosegman SA de CV</p>

          </div>
        </section>
      </footer>
    </div>
  )
}
